//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestiondeCursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestiondeCursos()
        {
            this.CursoporMatricula = new HashSet<CursoporMatricula>();
        }
    
        public int IDGestiondeCursos { get; set; }
        public int IDcurso { get; set; }
        public int IDaula { get; set; }
        public int IDhorario { get; set; }
        public int IDprofesor { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
        public Nullable<int> usuarioModifica { get; set; }
        public Nullable<System.DateTime> Fechacrea { get; set; }
        public Nullable<bool> Indicador_Activo { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoporMatricula> CursoporMatricula { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
