//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotadeCredito
    {
        public int IDNOTACREDITO { get; set; }
        public Nullable<int> IDfactura { get; set; }
        public string claveNumerica { get; set; }
        public int idEstudiante { get; set; }
        public int IdMatricula { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<double> subtotal { get; set; }
        public double total { get; set; }
        public int cantidadCursos { get; set; }
        public int usuarioCrea { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipodePago { get; set; }
        public string Maestro { get; set; }
        public string Detalle { get; set; }
        public Nullable<bool> Indicador_Activo { get; set; }
    
        public virtual Facturacion Facturacion { get; set; }
        public virtual Matricula Matricula { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
    }
}
