//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Facturacion = new HashSet<Facturacion>();
            this.GestiondeCursos = new HashSet<GestiondeCursos>();
            this.GestionDePagos = new HashSet<GestionDePagos>();
            this.Matricula = new HashSet<Matricula>();
            this.NotadeCredito = new HashSet<NotadeCredito>();
        }
    
        public int IDpersona { get; set; }
        public string cedula { get; set; }
        public Nullable<int> tipo_identificacion { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public byte[] foto { get; set; }
        public Nullable<bool> estado { get; set; }
        public int idUsuario { get; set; }
        public int idRol { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
        public Nullable<int> usuarioModifica { get; set; }
        public Nullable<bool> Indicador_Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion> Facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestiondeCursos> GestiondeCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionDePagos> GestionDePagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotadeCredito> NotadeCredito { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipodeIdentificacion TipodeIdentificacion { get; set; }
    }
}
