//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FacturaDescripcion
    {
        public string nombre { get; set; }
        public int precio { get; set; }
        public string descripcion { get; set; }
        public int IDfactura { get; set; }
        public int IDmatricula { get; set; }
        public int IdEstudiante { get; set; }
    }
}
