//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Facturas
    {
        public int IDfactura { get; set; }
        public int idEstudiante { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public int IdMatricula { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public int cantidadCursos { get; set; }
        public double subtotal { get; set; }
        public double total { get; set; }
    }
}
